# Generated by Django 4.2.1 on 2023-05-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructure',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='name',
            new_name='nom',
        ),
    ]
